# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: [ "with_toc_data", "xhtml", "autolink" ]

gems:
  - jekyll-sitemap

# Site settings
title: "My Blog"
description: > # this means to ignore newlines until "email:"
  Things that came in my mind...

email: my@email.co
#blog logos
logo: "/assets/images/stpa-symbol.png"
logo_footer: "/assets/images/stpa-symbol.png"

# blog cover
cover: "/assets/images/cover.gif"

name: 'Dil Maquinista'
author: 'Dil Maquinista'
author_image: "http://www.sinsuv.com.br/adm/imagens/dilma.jpg"
author_bio: >
   Presidenta do Brasil

paginate: 5

url: "https://meditator.stpa.co" # the base hostname & protocol for your site
excerpt_separator: "<!-- more -->"

comments: true

# readtime properties
# ---------------------
readtime: true
wpm:      200

baseurl: ""

# social icons and sharing options
social:
#  - icon:  twitter
#    url: https://twitter.com/stewones
#    desc: Follow me on Twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon: facebook
#    url:  https://facebook.com/stewones
#   desc: Connect me at Facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/stpa-co
    desc: Fork me on GitHub
    share_url: 
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://plus.google.com/118319296239885590925/posts
#    desc:  Add me on Google+
#    share_url:
#    share_title:
#    share_link:
